language: csharp
sudo: required
dotnet: 2.1.300
solution: ./CourseProject.sln
dist: trusty 

install:
  - dotnet restore ./CourseProject.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./Gateway/Gateway.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./UnitTests/bin/Debug/netcoreapp2.1/UnitTests.dll


script:  
  dotnet build ./Gateway/Gateway.sln -c Release